[ -f ~/.aliases.sh ] && source ~/.aliases.sh

# aws
export EC2_PEM=~/.ssh/ec2.pem
alias ec2g='~/bin/ec2g.sh'
alias ec2stop='aws ec2 stop-instances --instance-ids i-0ffccfb4ce40e551d'
alias ec2start='aws ec2 start-instances --instance-ids i-0ffccfb4ce40e551d'
alias ec2ip="aws ec2 describe-instances --filters Name=instance-id,Values=i-0ffccfb4ce40e551d --region us-west-2 --output text --query 'Reservations[*].Instances[*].NetworkInterfaces[*].Association.PublicIp'"
alias artifact='aws codeartifact login --domain calypsoai --repo vespr --tool pip'

# python from git-bash: https://stackoverflow.com/a/36530750/3585557
alias python='winpty python.exe'
alias ipython='winpty ipython.exe'

# solarized mintty theme
# [ -f ~/.mintty-solarized-dark ] && source ~/.mintty-solarized-dark
# [ -f ~/.mintty-solarized-light ] && source ~/.mintty-solarized-light

# network items
alias ifconfig='ipconfig'

alias bashrc='emacs -nw ~/.bashrc && source ~/.bashrc'

alias ..='cd ..'
alias ...='cd ../..'
alias ...='cd ../../..'
alias ....='cd ../../../..'
# alias /='cd /'
alias ~='cd ~'

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# # solarized dark (from https://github.com/karlin/mintty-colors-solarized)
# echo -ne '\e]4;0;#073642\a'   # black
# echo -ne '\e]4;1;#dc322f\a'   # red
# echo -ne '\e]4;2;#859900\a'   # green
# echo -ne '\e]4;3;#b58900\a'   # yellow
# echo -ne '\e]4;4;#268bd2\a'   # blue
# echo -ne '\e]4;5;#d33682\a'   # magenta
# echo -ne '\e]4;6;#2aa198\a'   # cyan
# echo -ne '\e]4;7;#eee8d5\a'   # white (light grey really)
# echo -ne '\e]4;8;#002b36\a'   # bold black (i.e. dark grey)
# echo -ne '\e]4;9;#cb4b16\a'   # bold red
# echo -ne '\e]4;10;#586e75\a'  # bold green
# echo -ne '\e]4;11;#657b83\a'  # bold yellow
# echo -ne '\e]4;12;#839496\a'  # bold blue
# echo -ne '\e]4;13;#6c71c4\a'  # bold magenta
# echo -ne '\e]4;14;#93a1a1\a'  # bold cyan
# echo -ne '\e]4;15;#fdf6e3\a'  # bold white
# echo -ne '\e]10;#eee8d5\a'  # foreground
# echo -ne '\e]11;#002b36\a'  # background
# echo -ne '\e]12;#859900\a'  # cursor

# # # solarized light (from https://github.com/karlin/mintty-colors-solarized)
# # echo -ne '\e]4;0;#073642\a'   # black
# # echo -ne '\e]4;1;#dc322f\a'   # red
# # echo -ne '\e]4;2;#859900\a'   # green
# # echo -ne '\e]4;3;#b58900\a'   # yellow
# # echo -ne '\e]4;4;#268bd2\a'   # blue
# # echo -ne '\e]4;5;#d33682\a'   # magenta
# # echo -ne '\e]4;6;#2aa198\a'   # cyan
# # echo -ne '\e]4;7;#eee8d5\a'   # white (light grey really)
# # echo -ne '\e]4;8;#002b36\a'   # bold black (i.e. dark grey)
# # echo -ne '\e]4;9;#cb4b16\a'   # bold red
# # echo -ne '\e]4;10;#586e75\a'  # bold green
# # echo -ne '\e]4;11;#657b83\a'  # bold yellow
# # echo -ne '\e]4;12;#839496\a'  # bold blue
# # echo -ne '\e]4;13;#6c71c4\a'  # bold magenta
# # echo -ne '\e]4;14;#93a1a1\a'  # bold cyan
# # echo -ne '\e]4;15;#fdf6e3\a'  # bold white
# # echo -ne '\e]10;#586e75\a'  # foreground
# # echo -ne '\e]11;#fdf6e3\a'  # background
# # echo -ne '\e]12;#eee8d5\a'  # cursor

export PROMPT_DIRTRIM=3
export PS1='\e[43m\e[30m\u @ \h\e[0m \[\e[34m\w\] \[\e[32m>\e[m '

# # conda initialize, generated by running `conda init bash`
# [ -f /c/Users/schowell/Miniconda3/Scripts/conda.exe ] && eval "$('/c/Users/schowell/Miniconda3/Scripts/conda.exe' 'shell.bash' 'hook')"
# [ -f /c/Users/showell/Miniconda3/Scripts/conda.exe ] && eval "$('/c/Users/showell/Miniconda3/Scripts/conda.exe' 'shell.bash' 'hook')"
# [ -f /c/Users/showell/AppData/Local/miniforge-pypy3/Scripts/conda.exe ] && eval "$('/c/Users/showell/AppData/Local/miniforge-pypy3/Scripts/conda.exe' 'shell.bash' 'hook')"
# # [ -f /c/ProgramData/Anaconda3/Scripts/conda.exe ] && eval "$('/c/ProgramData/Anaconda3/Scripts/conda.exe' 'shell.bash' 'hook')"
