source ~/.aliases.zsh

# added for dot-file repo: config
alias config='/mingw64/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

# vespr
# VESPR_USER='steven@calypsoai.com'
# VESPR_PASS='wXAqSh9Y3sbRbdK'

# aws
export GPU_EC2_PEM=~/.ssh/gpu-ec2-instance.pem
alias ec2g='~/bin/ec2g.sh'
alias ec2stop='aws ec2 stop-instances --instance-ids i-0ffccfb4ce40e551d'
alias ec2start='aws ec2 start-instances --instance-ids i-0ffccfb4ce40e551d'
alias ec2ip="aws ec2 describe-instances --filters Name=instance-id,Values=i-0ffccfb4ce40e551d --region us-west-2 --output text --query 'Reservations[*].Instances[*].NetworkInterfaces[*].Association.PublicIp'"
alias artifact='aws codeartifact login --domain calypsoai --repo vespr --tool pip'

# conda initialize, generated by running `conda init bash`
eval "$('/c/Users/schowell/Miniconda3/Scripts/conda.exe' 'shell.bash' 'hook')"

# python from git-bash: https://stackoverflow.com/a/36530750/3585557
alias python='winpty python.exe'
alias ipython='winpty ipython.exe'

# solarized mintty theme
source ~/.mintty-solarized-dark
# source .mintty-solarized-light

# network items
alias ifconfig='ipconfig'

alias bashrc='vim ~/.bashrc && source ~/.bashrc'

alias ..='cd ..'
alias ...='cd ../..'
alias ...='cd ../../..'
alias ....='cd ../../../..'
alias /='cd /'
alias ~='cd ~'
